version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-bot
    depends_on:
      - selenoid
      - db
    network_mode: bridge
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - SELENOID_URL=http://host.docker.internal:4444/wd/hub
      # проверить конфликт с .env
      - DB_HOST="db"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      # если работаем не от root
      # MYSQL_USER: "${DB_USER}"
      # MYSQL_PASSWORD: "${DB_PASSWORD}"
    # volumes:
    # директория с данными
    #  - /my/own/datadir:/var/lib/mysql
    # есть возможность при создании выполнить скрипты инициализации (миграции)
    # docs https://hub.docker.com/_/mysql
    # - ./mysql_migrations:/docker-entrypoint-initdb.d:ro

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    network_mode: bridge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/config:/etc/selenoid/"
    env_file:
      - .env
    ports:
      - "4444:4444"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command:
      - "--selenoid-uri"
      - "http://host.docker.internal:4444"
    extra_hosts:
      - "host.docker.internal:host-gateway"
